resources:
  repositories:
    - repository: Templates
      type: github
      ref: 'refs/heads/master'
      name: "HoeflingSoftware/DevOps.Templates"
      endpoint: ahoefling

trigger:
  branches:
    include:
      - master
      - refs/tags/*
      
variables:
  majorMinorPatch: 1.0.0
  revision: $[counter(variables['majorMinorPatch'], 0)]
  system.debug: "true"
  githubOrganization: 'HoeflingSoftware'
  githubRepo: 'Dnn.KeyMaster'

jobs:    
- job: Build
  displayName: Build and Create Installer
  pool:
    name: Hosted VS2017
    demands:
    - MSBuild

  steps:
  - powershell: '$(System.DefaultWorkingDirectory)\build.ps1 -Target Package -ScriptArgs "-package_version=$env:VERSION"; exit $LASTEXITCODE'
    env:
      VERSION: "$(majorMinorPatch).$(revision)"
    displayName: 'Cake Build - Clean, NuGet, Build and Package'

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*_install.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- job: Release
  dependsOn: Build
  displayName: Release
  pool:
    name: "Hosted VS2017"
  condition: and(succeeded(), startswith(variables['Build.SourceBranch'], 'refs/tags'))

  steps:
  - template: GitHub/azure-pipelines.yml@Templates
    parameters:
      githubOrganization: '$(githubOrganization)'
      githubRepo: '$(githubRepo)'
      githubToken: '$(githubToken)'
      publishedArtifactPath: '*_install.zip'
      publishedArtifactDisplayName: '$(githubRepo)_$(majorMinorPatch).$(revision)_install.zip'