trigger:
  branches:
    include:
      - master
      
variables:
  major: 0
  minor: 0
  patch: 0
  revision: $[counter('versioncounter', 0)]
  system.debug: "true"
  githubOrganization: 'HoeflingSoftware'
  githubRepo: 'Dnn.KeyMaster'

jobs:
- job: PreBuild
  displayName: Get Build variables
  pool:
    name: Hosted VS2017

  steps:
  - powershell: |
      $tag = (git tag -l --points-at HEAD)
      if ($tag -ne '') {
        Write-Host "##vso[Release.Tag]$tag"
      }
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Get Build Tag

  - powershell: Write-Host "##vso[Version]$(major).$(minor).$(patch).$(revision)"
    displayName: Get Build Number

- job: Build
  dependsOn: PreBuild
  displayName: Build and Create Installer
  pool:
    name: Hosted VS2017
    demands:
    - MSBuild

  steps:
  - powershell: '$(System.DefaultWorkingDirectory)\build.ps1 -Target Package -ScriptArgs "-package_version=$(Version)"; exit $LASTEXITCODE'
    displayName: 'Cake Build - Clean, NuGet, Build and Package'

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*_install.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

# this job is scaffolded out and we need to do more work before it is ready
- job: Release
  dependsOn: Build
  displayName: GitHub Release
  pool:
    name: "Hosted VS2017"
  condition: and(succeeded(), ne(variables['Tag'], ''))

  steps:
  - task: Npm@1
    displayName: 'npm install github-release-notes'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install github-release-notes -g'

  - powershell: 'gren release --username=$(githubOrganization) --token=$env:TOKEN --repo=$(githubRepo); exit $LASTEXITCODE'
    env:
      TOKEN: $(githubToken)
    displayName: 'gren release'

