trigger:
  branches:
    include:
      - master
      - refs/heads/*
      - refs/tags/*
      
variables:
  major: 1
  minor: 0
  patch: 0
  revision: $[counter('versioncounter', 0)]
  system.debug: "true"
  githubOrganization: 'HoeflingSoftware'
  githubRepo: 'Dnn.KeyMaster'

jobs:
- job: Build
  displayName: Build and Create Installer
  pool:
    name: Hosted VS2017
    demands:
    - MSBuild

  steps:
  - powershell: '$(System.DefaultWorkingDirectory)\BuildUtilities\getBuildVariables.ps1; exit $LASTEXITCODE' 
    displayName: Build Variables

  - powershell: '$(System.DefaultWorkingDirectory)\build.ps1 -Target Package -ScriptArgs "-package_version=$env:VERSION"; exit $LASTEXITCODE'
    env:
      VERSION: "$(major).$(minor).$(patch).$(revision)"
    displayName: 'Cake Build - Clean, NuGet, Build and Package'

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*_install.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

# this job is scaffolded out and we need to do more work before it is ready
- job: Release
  dependsOn: Build
  displayName: Release
  pool:
    name: "Hosted VS2017"
    # todo - add a conditional that excludes all Pull Requests

  steps:
  - powershell: '$(System.DefaultWorkingDirectory)\BuildUtilities\getBuildVariables.ps1; exit $LASTEXITCODE' 
    displayName: Build Variables

  - powershell: Write-Host "Hello World"

  - powershell: SKip this steps
    condition: and(succeeded(), ne(variables['tag'], ''))
  #- task: Npm@1
  #  displayName: 'npm install github-release-notes'
  #  inputs:
  #    command: custom
  #    verbose: false
  #    customCommand: 'install github-release-notes -g'

  #- powershell: 'gren release --username=$(githubOrganization) --token=$env:TOKEN --repo=$(githubRepo); exit $LASTEXITCODE'
  #  env:
  #    TOKEN: $(githubToken)
  #  displayName: 'gren release'

